# Generated by Django 6.0.8 on 2026-08-16 02:00

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('device_key', models.CharField(max_length=160, unique=True)),
                ('state', models.CharField(choices=[('unpaired', 'Ikke parret'), ('offline', 'Offline'), ('ready', 'Klar'), ('armed', 'Auto klar'), ('recording', 'Optager'), ('finalizing', 'Gemmer')], default='unpaired', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('free_storage_bytes', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('queued_uploads', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gymnast',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=100)),
                ('kiga_id', models.CharField(blank=True, max_length=120)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gymnasts', to='wagvid_app.level')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gymnasts', to='wagvid_app.organization')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('routine', 'Hel øvelse'), ('training', 'Træning'), ('drill', 'Moment'), ('competition', 'Konkurrence')], max_length=20)),
                ('state', models.CharField(choices=[('queued', 'Venter'), ('uploading', 'Uploader'), ('stored', 'Gemt'), ('quarantined', 'Karantæne'), ('unusable', 'Ubrugelig')], default='queued', max_length=20)),
                ('object_key', models.CharField(blank=True, max_length=500)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('original_retained', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField()),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='wagvid_app.device')),
                ('gymnast', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media', to='wagvid_app.gymnast')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='wagvid_app.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='level',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='wagvid_app.organization'),
        ),
        migrations.CreateModel(
            name='ExchangeJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('import', 'Import'), ('export', 'Eksport')], max_length=10)),
                ('kind', models.CharField(max_length=80)),
                ('state', models.CharField(choices=[('draft', 'Kladde'), ('validating', 'Validerer'), ('ready', 'Klar'), ('running', 'Kører'), ('failed', 'Fejlet'), ('completed', 'Færdig')], default='draft', max_length=20)),
                ('schema_version', models.CharField(max_length=40)),
                ('result_summary', models.JSONField(default=dict)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_jobs', to='wagvid_app.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='wagvid_app.organization'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=120)),
                ('object_type', models.CharField(max_length=120)),
                ('object_id', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('metadata', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='wagvid_app.organization')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('draft', 'Kladde'), ('queued', 'Venter'), ('blocked', 'Blokeret'), ('running', 'Kører'), ('needs-review', 'Kræver review'), ('failed-retryable', 'Kan prøves igen'), ('failed-terminal', 'Stoppet'), ('completed', 'Færdig'), ('cancelled', 'Annulleret')], default='draft', max_length=24)),
                ('scope', models.CharField(max_length=32)),
                ('rulepack_id', models.CharField(max_length=200)),
                ('model_profile', models.CharField(max_length=120)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('revision', models.PositiveIntegerField(default=1)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_jobs', to='wagvid_app.mediaasset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='wagvid_app.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('system-admin', 'Systemadministrator'), ('organization-admin', 'Organisationsadministrator'), ('operator', 'Operatør'), ('coach', 'Træner'), ('reviewer', 'Reviewer'), ('researcher', 'Forsker'), ('viewer', 'Læser')], max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wagvid_memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='wagvid_app.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='one_membership_per_org')],
            },
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_level_per_org'),
        ),
        migrations.AddConstraint(
            model_name='gymnast',
            constraint=models.UniqueConstraint(fields=('organization', 'license_number'), name='unique_license_per_org'),
        ),
        migrations.AddConstraint(
            model_name='analysisjob',
            constraint=models.UniqueConstraint(fields=('media', 'revision'), name='unique_analysis_revision'),
        ),
    ]
