# Generated by Django 5.2.17 on 2026-08-16 09:07

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagvid_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('state', models.CharField(choices=[('online', 'Online'), ('draining', 'Dræner'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('capabilities', models.JSONField(default=list)),
                ('active_jobs', models.PositiveIntegerField(default=0)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Advarsel'), ('critical', 'Kritisk')], max_length=12)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_alerts', to='wagvid_app.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['active', 'severity'], name='wagvid_app__active_42a72d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capture_id', models.UUIDField()),
                ('idempotency_key', models.CharField(max_length=160)),
                ('local_filename', models.CharField(max_length=255)),
                ('expected_bytes', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('received_bytes', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_sha256', models.CharField(max_length=64)),
                ('object_key', models.CharField(blank=True, max_length=500)),
                ('state', models.CharField(choices=[('open', 'Åben'), ('uploading', 'Uploader'), ('verifying', 'Verificerer'), ('completed', 'Færdig'), ('failed', 'Fejlet')], default='open', max_length=20)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_sessions', to='wagvid_app.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='wagvid_app.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='unique_upload_idempotency_per_org'), models.CheckConstraint(condition=models.Q(('received_bytes__lte', models.F('expected_bytes'))), name='upload_received_not_above_expected')],
            },
        ),
    ]
