# Generated by Django 5.2.17 on 2026-08-16 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagvid_app", "0002_workernode_systemalert_uploadsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisjob",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analysisjob",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="analysisjob",
            name="leased_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leased_jobs",
                to="wagvid_app.workernode",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="api_token_hash",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="uploadsession",
            name="gymnast",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="upload_sessions",
                to="wagvid_app.gymnast",
            ),
        ),
        migrations.AddField(
            model_name="uploadsession",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("routine", "Hel øvelse"),
                    ("training", "Træning"),
                    ("drill", "Moment"),
                    ("competition", "Konkurrence"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="uploadsession",
            name="recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
