# Generated by Django 5.2.17 on 2026-08-16 09:51

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagvid_app', '0003_analysisjob_attempts_analysisjob_lease_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('draft-ai', 'AI-kladde'), ('needs-review', 'Kræver review'), ('human-confirmed', 'Menneskeligt godkendt'), ('panel-confirmed', 'Panelgodkendt'), ('frozen', 'Låst')], default='draft-ai', max_length=24)),
                ('proposed_d_score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('proposed_e_score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('proposed_neutral', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('proposed_final_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('score_ledger', models.JSONField(default=dict)),
                ('model_run', models.JSONField(default=dict)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='wagvid_app.analysisjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeductionCandidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criterion', models.CharField(max_length=200)),
                ('rule_reference', models.CharField(max_length=200)),
                ('start_ms', models.PositiveIntegerField()),
                ('end_ms', models.PositiveIntegerField()),
                ('proposed_amount', models.DecimalField(decimal_places=3, max_digits=4)),
                ('model_confidence', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('evidence', models.JSONField(default=dict)),
                ('review_state', models.CharField(choices=[('pending', 'Afventer'), ('accepted', 'Godkendt'), ('rejected', 'Afvist'), ('corrected', 'Rettet')], default='pending', max_length=20)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='wagvid_app.analysisresult')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('kind', models.CharField(choices=[('competition', 'Konkurrence'), ('training', 'Træning'), ('test', 'Test')], max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=240)),
                ('external_source', models.CharField(blank=True, max_length=80)),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wagvid_app.organization')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('accept-ai', 'AI-forslag godkendt'), ('accept-official', 'Officiel bedømmelse godkendt'), ('correct-ai', 'AI rettet'), ('official-error', 'Mulig officiel dommerfejl'), ('inconclusive', 'Utilstrækkelig evidens')], max_length=24)),
                ('accepted_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='wagvid_app.deductioncandidate')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apparatus', models.CharField(choices=[('VT', 'Spring'), ('UB', 'Forskudt barre'), ('BB', 'Bom'), ('FX', 'Gulv')], max_length=2)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('start_order', models.PositiveIntegerField(blank=True, null=True)),
                ('rulepack_id', models.CharField(max_length=200)),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('official_d_score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('official_e_score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('official_neutral', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('official_final_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('official_frozen_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routines', to='wagvid_app.event')),
                ('gymnast', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routines', to='wagvid_app.gymnast')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='wagvid_app.organization')),
            ],
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='wagvid_app.routine'),
        ),
        migrations.AddConstraint(
            model_name='deductioncandidate',
            constraint=models.CheckConstraint(condition=models.Q(('end_ms__gte', models.F('start_ms'))), name='deduction_time_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('event', 'external_id'), name='unique_external_routine_per_event'),
        ),
    ]
