# Generated by Django 5.2.17 on 2026-08-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagvid_app', '0004_analysisresult_deductioncandidate_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymnast',
            name='discipline',
            field=models.CharField(choices=[('WAG', 'Kvindeidrætsgymnastik'), ('MAG', 'Mandlig idrætsgymnastik')], default='WAG', max_length=3),
        ),
        migrations.AlterField(
            model_name='routine',
            name='apparatus',
            field=models.CharField(choices=[('VT', 'Spring'), ('UB', 'Forskudt barre'), ('BB', 'Bom'), ('FX', 'Gulv'), ('PH', 'Hest med bøjler'), ('SR', 'Ringe'), ('PB', 'Parallelle barrer'), ('HB', 'Reck')], max_length=2),
        ),
    ]
