# Generated by Django 5.2.17 on 2026-08-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagvid_app', '0005_gymnast_discipline_alter_routine_apparatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='client_request_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddConstraint(
            model_name='analysisjob',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id', ''), _negated=True), fields=('organization', 'client_request_id'), name='unique_analysis_request_per_org'),
        ),
    ]
