# Generated by Django 5.2.17 on 2026-08-16 15:58

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagvid_app', '0006_analysisjob_client_request_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisProgressEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('stage', models.CharField(max_length=80)),
                ('progress_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('message', models.CharField(blank=True, max_length=500)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_events', to='wagvid_app.analysisjob')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_events', to='wagvid_app.workernode')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('analysis_job', 'sequence'), name='unique_analysis_progress_sequence')],
            },
        ),
    ]
