# Generated by Django 5.2.17 on 2026-08-16 16:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagvid_app', '0007_analysisprogressevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreComparisonReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('official-confirmed', 'Officielt resultat bekræftet'), ('ai-discrepancy', 'AI-afvigelse bør undersøges'), ('corrected-labels', 'Korrigerede læringsetiketter'), ('inconclusive', 'Utilstrækkelig evidens')], max_length=24)),
                ('accepted_d_score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('accepted_e_score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('accepted_neutral', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('accepted_final_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_reviews', to='wagvid_app.analysisresult')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
