# Generated by Django 5.2.17 on 2026-08-16 16:49

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagvid_app', '0008_scorecomparisonreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='active_capture_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='app_version',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='device',
            name='battery_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='device',
            name='network_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='DevicePairingSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=256)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairing_session', to='wagvid_app.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_pairing_sessions', to='wagvid_app.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command', models.CharField(choices=[('arm', 'Armér auto'), ('disarm', 'Deaktivér auto'), ('start', 'Start optagelse'), ('stop', 'Stop optagelse')], max_length=16)),
                ('state', models.CharField(choices=[('pending', 'Afventer'), ('delivered', 'Leveret'), ('accepted', 'Accepteret'), ('rejected', 'Afvist'), ('expired', 'Udløbet')], default='pending', max_length=16)),
                ('expected_device_state', models.CharField(choices=[('unpaired', 'Ikke parret'), ('offline', 'Offline'), ('ready', 'Klar'), ('armed', 'Auto klar'), ('recording', 'Optager'), ('finalizing', 'Gemmer')], max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_code', models.CharField(blank=True, max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='wagvid_app.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_commands', to='wagvid_app.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('device', 'idempotency_key'), name='unique_device_command_request')],
            },
        ),
    ]
