# Generated by Django 5.2.17 on 2026-08-16 17:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagvid_app', '0009_device_active_capture_id_device_app_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='event',
            name='competition_level',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='federation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='rule_profile',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='timezone_name',
            field=models.CharField(default='Europe/Copenhagen', max_length=80),
        ),
        migrations.AddField(
            model_name='routine',
            name='age_category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='routine',
            name='performed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='rotation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='round_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='ExternalMediaReference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='KIGA', max_length=80)),
                ('external_media_id', models.CharField(max_length=200)),
                ('download_uri', models.URLField(max_length=1000)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('captured_at', models.DateTimeField()),
                ('content_type', models.CharField(max_length=120)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('camera_id', models.CharField(blank=True, max_length=120)),
                ('view', models.CharField(blank=True, max_length=120)),
                ('download_allowed', models.BooleanField()),
                ('analysis_allowed', models.BooleanField()),
                ('training_allowed', models.BooleanField()),
                ('retention_until', models.DateField(blank=True, null=True)),
                ('consent_reference', models.CharField(blank=True, max_length=240)),
                ('access_policy', models.CharField(blank=True, max_length=240)),
                ('state', models.CharField(choices=[('discovered', 'Fundet'), ('ready', 'Klar til hentning'), ('imported', 'Importeret'), ('blocked', 'Blokeret')], default='discovered', max_length=20)),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_sources', to='wagvid_app.mediaasset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_media_references', to='wagvid_app.organization')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_media_references', to='wagvid_app.routine')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'provider', 'external_media_id'), name='unique_external_media_per_provider')],
            },
        ),
        migrations.CreateModel(
            name='OfficialResultSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=80)),
                ('source', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('provisional', 'Foreløbig'), ('official', 'Officiel'), ('corrected', 'Korrigeret'), ('withdrawn', 'Tilbagetrukket')], max_length=20)),
                ('result_version', models.CharField(max_length=120)),
                ('d_score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('e_score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('artistry', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('neutral', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('final_score', models.DecimalField(decimal_places=3, max_digits=6)),
                ('source_captured_at', models.DateTimeField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='official_versions', to='wagvid_app.routine')),
            ],
            options={
                'ordering': ['-source_captured_at'],
                'constraints': [models.UniqueConstraint(fields=('routine', 'provider', 'result_version'), name='unique_official_result_version')],
            },
        ),
    ]
