# Generated by Django for Ai.WAGVID membership invitations.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagvid_app", "0011_mediaasset_source_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipInvitation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system-admin", "Systemadministrator"),
                            ("organization-admin", "Organisationsadministrator"),
                            ("operator", "Operatør"),
                            ("coach", "Træner"),
                            ("reviewer", "Reviewer"),
                            ("researcher", "Forsker"),
                            ("viewer", "Læser"),
                        ],
                        max_length=32,
                    ),
                ),
                ("token_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wagvid_membership_invitations_accepted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wagvid_membership_invitations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_invitations",
                        to="wagvid_app.organization",
                    ),
                ),
            ],
            options={
                "db_table": "wagvid_app_membershipinvitation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="membershipinvitation",
            index=models.Index(fields=["organization", "email"], name="invite_org_email_idx"),
        ),
        migrations.AddIndex(
            model_name="membershipinvitation",
            index=models.Index(fields=["organization", "expires_at"], name="invite_org_exp_idx"),
        ),
    ]
