# Generated by Django 5.2.17 on 2026-08-28 20:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagvid_app', '0014_backup_upgrade_review_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('system-admin', 'Systemadministrator'), ('organization-admin', 'Organisationsadministrator'), ('operator', 'Operatør'), ('coach', 'Træner'), ('reviewer', 'Reviewer'), ('domain-reviewer', 'Fagkyndig reviewer'), ('annotator', 'Annotator'), ('researcher', 'Forsker'), ('viewer', 'Læser')], max_length=32),
        ),
        migrations.CreateModel(
            name='EvidenceShareGrant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.CharField(max_length=320)),
                ('actions', models.JSONField(default=list)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_evidence_grants', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_grants', to='wagvid_app.mediaasset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_share_grants', to='wagvid_app.organization')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_evidence_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('system-admin', 'Systemadministrator'), ('organization-admin', 'Organisationsadministrator'), ('operator', 'Operatør'), ('coach', 'Træner'), ('reviewer', 'Reviewer'), ('domain-reviewer', 'Fagkyndig reviewer'), ('annotator', 'Annotator'), ('researcher', 'Forsker'), ('viewer', 'Læser')], max_length=32)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('state', models.CharField(choices=[('pending', 'Afventer'), ('accepted', 'Accepteret'), ('revoked', 'Tilbagekaldt'), ('expired', 'Udløbet')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_wagvid_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_wagvid_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='wagvid_app.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigurationRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=100)),
                ('revision', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('draft', 'Kladde'), ('frozen', 'Frosset'), ('superseded', 'Erstattet')], default='draft', max_length=16)),
                ('values', models.JSONField(default=dict)),
                ('digest', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuration_revisions', to='wagvid_app.organization')),
            ],
            options={
                'ordering': ['namespace', '-revision'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'namespace', 'revision'), name='unique_configuration_revision')],
            },
        ),
        migrations.CreateModel(
            name='DatasetGovernanceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_reference', models.CharField(max_length=500)),
                ('immutable_digest', models.CharField(max_length=64)),
                ('rights_reference', models.CharField(max_length=500)),
                ('consent_reference', models.CharField(blank=True, max_length=500)),
                ('analysis_allowed', models.BooleanField(default=False)),
                ('retention_allowed', models.BooleanField(default=False)),
                ('training_allowed', models.BooleanField(default=False)),
                ('export_allowed', models.BooleanField(default=False)),
                ('pseudonymous_athlete_key', models.CharField(max_length=64)),
                ('pseudonymous_event_key', models.CharField(max_length=64)),
                ('split_manifest_digest', models.CharField(blank=True, max_length=64)),
                ('label_provenance', models.JSONField(default=dict)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_governance_records', to='wagvid_app.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'immutable_digest'), name='unique_dataset_digest_per_org')],
            },
        ),
    ]
