# Generated by Django 5.2.17 on 2026-08-28 20:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagvid_app', '0015_alter_membership_role_evidencesharegrant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionBatchRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('planned', 'Planlagt'), ('queued', 'I kø'), ('running', 'Kører'), ('frozen', 'AI frosset'), ('official-revealed', 'Officielt resultat frigivet'), ('completed', 'Færdig'), ('failed', 'Fejlet')], default='planned', max_length=24)),
                ('analysis_profile_digest', models.CharField(max_length=64)),
                ('plan_digest', models.CharField(max_length=64, unique=True)),
                ('task_count', models.PositiveIntegerField()),
                ('excluded_count', models.PositiveIntegerField()),
                ('control_plan', models.JSONField(default=dict)),
                ('failure_code', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_batches', to='wagvid_app.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_batches', to='wagvid_app.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisDeliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('score-verification', 'Scoreverifikation'), ('performance', 'Performance'), ('longitudinal', 'Longitudinal'), ('event-summary', 'Konkurrencesammendrag')], max_length=24)),
                ('schema_id', models.CharField(max_length=120)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('payload_digest', models.CharField(max_length=64)),
                ('provenance', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to='wagvid_app.analysisjob')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to='wagvid_app.event')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('gymnast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to='wagvid_app.gymnast')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_deliverables', to='wagvid_app.organization')),
            ],
            options={
                'ordering': ['-generated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('analysis_job__isnull', False)), fields=('analysis_job', 'kind', 'revision'), name='unique_job_deliverable_revision')],
            },
        ),
    ]
