# Generated by Django 5.2.17 on 2026-08-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagvid_app', '0016_competitionbatchrun_analysisdeliverable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisdeliverable',
            name='kind',
            field=models.CharField(choices=[('score-verification', 'Scoreverifikation'), ('performance', 'Performance'), ('longitudinal', 'Longitudinal'), ('event-summary', 'Konkurrencesammendrag'), ('temporal-recognition', 'Tidslig genkendelse'), ('dscore-ledger', 'D-score-ledger'), ('deduction-ledger', 'Fradragsledger'), ('apparatus-analysis', 'Apparatusanalyse'), ('validation-manifest', 'Valideringsmanifest')], max_length=24),
        ),
    ]
