# Generated by Django 5.2.17 on 2026-08-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagvid_app', '0018_membershipinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipinvitation',
            name='role',
            field=models.CharField(choices=[('system-admin', 'Systemadministrator'), ('organization-admin', 'Organisationsadministrator'), ('operator', 'Operatør'), ('coach', 'Træner'), ('reviewer', 'Reviewer'), ('domain-reviewer', 'Fagkyndig reviewer'), ('annotator', 'Annotator'), ('researcher', 'Forsker'), ('viewer', 'Læser')], max_length=32),
        ),
    ]
