# Generated by Django 5.2.17 on 2026-08-29 08:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagvid_app', '0019_alter_membershipinvitation_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceAnnotationRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('routine', 'Routine'), ('phase', 'Fase'), ('element', 'Element'), ('contact', 'Kontakt'), ('landing', 'Landing'), ('deduction', 'Fradrag'), ('comment', 'Kommentar')], max_length=16)),
                ('label', models.CharField(max_length=240)),
                ('state', models.CharField(choices=[('draft', 'Kladde'), ('submitted', 'Til review'), ('accepted', 'Godkendt'), ('rejected', 'Afvist')], default='draft', max_length=16)),
                ('source_sha256', models.CharField(max_length=64)),
                ('timeline_digest', models.CharField(max_length=64)),
                ('stream_index', models.PositiveIntegerField(default=0)),
                ('start_frame_index', models.PositiveIntegerField()),
                ('end_frame_index', models.PositiveIntegerField()),
                ('start_timestamp_ticks', models.BigIntegerField()),
                ('end_timestamp_ticks', models.BigIntegerField()),
                ('time_base_numerator', models.PositiveIntegerField()),
                ('time_base_denominator', models.PositiveIntegerField()),
                ('calibration', models.JSONField(default=dict)),
                ('attributes', models.JSONField(default=dict)),
                ('rule_reference', models.CharField(blank=True, max_length=240)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotation_revisions', to='wagvid_app.analysisjob')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_annotations', to='wagvid_app.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='wagvid_app.evidenceannotationrevision')),
            ],
            options={
                'ordering': ['start_frame_index', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('analysis_job', 'parent', 'revision'), name='unique_annotation_revision'), models.CheckConstraint(condition=models.Q(('end_frame_index__gte', models.F('start_frame_index'))), name='annotation_frame_order'), models.CheckConstraint(condition=models.Q(('end_timestamp_ticks__gte', models.F('start_timestamp_ticks'))), name='annotation_tick_order')],
            },
        ),
    ]
