# Generated by Django 5.2.17 on 2026-08-29 09:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagvid_app', '0020_evidenceannotationrevision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkCamera',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(choices=[('dahua', 'Dahua'), ('onvif', 'Generisk ONVIF')], max_length=16)),
                ('endpoint', models.URLField(max_length=300)),
                ('username_secret_ref', models.CharField(max_length=200)),
                ('password_secret_ref', models.CharField(max_length=200)),
                ('tls_verify', models.BooleanField(default=True)),
                ('state', models.CharField(choices=[('configured', 'Konfigureret'), ('online', 'Online'), ('degraded', 'Begrænset'), ('offline', 'Offline'), ('disabled', 'Deaktiveret')], default='configured', max_length=16)),
                ('stable_device_id', models.CharField(blank=True, max_length=160)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('firmware', models.CharField(blank=True, max_length=120)),
                ('capability_snapshot', models.JSONField(default=dict)),
                ('capability_digest', models.CharField(blank=True, max_length=64)),
                ('canonical_profile_id', models.CharField(blank=True, max_length=120)),
                ('preview_profile_id', models.CharField(blank=True, max_length=120)),
                ('apparatus', models.CharField(blank=True, choices=[('VT', 'Spring'), ('UB', 'Forskudt barre'), ('BB', 'Bom'), ('FX', 'Gulv'), ('PH', 'Hest med bøjler'), ('SR', 'Ringe'), ('PB', 'Parallelle barrer'), ('HB', 'Reck')], max_length=8)),
                ('preset_id', models.CharField(blank=True, max_length=120)),
                ('calibration_digest', models.CharField(blank=True, max_length=64)),
                ('calibration_valid', models.BooleanField(default=False)),
                ('tracking_mode', models.CharField(choices=[('off', 'Fra'), ('manual', 'Manuel PTZ'), ('native', 'Kameraets auto-tracking'), ('wagvid-assisted', 'Ai.WAGVID-assisteret')], default='off', max_length=20)),
                ('ptz_owner', models.CharField(default='none', max_length=24)),
                ('ptz_generation', models.PositiveIntegerField(default=0)),
                ('last_probe_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('enabled', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_cameras', to='wagvid_app.organization')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkCameraAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.CharField(choices=[('accepted', 'Accepteret'), ('rejected', 'Afvist'), ('failed', 'Fejlet')], max_length=16)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='wagvid_app.networkcamera')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_camera_actions', to='wagvid_app.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='networkcamera',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_network_camera_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='networkcamera',
            constraint=models.UniqueConstraint(condition=models.Q(('stable_device_id', ''), _negated=True), fields=('organization', 'stable_device_id'), name='unique_network_camera_device_id_per_org'),
        ),
    ]
