# Generated by Django 5.2.17 on 2026-08-29 09:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagvid_app', '0021_networkcamera_networkcameraaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KigaNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_ref', models.CharField(max_length=240)),
                ('event_type', models.CharField(default='analysis.batch-ready', max_length=80)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('export_digest', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('pending', 'Afventer levering'), ('delivered', 'Leveret'), ('failed', 'Fejlet')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kiga_notifications', to='wagvid_app.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiga_notifications', to='wagvid_app.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='unique_kiga_notification_idempotency_per_org')],
            },
        ),
    ]
