from django.urls import path

from . import (
    analysis_api,
    annotation_views,
    device_api,
    governance_views,
    invitation_views,
    master_data_views,
    media_access,
    media_timeline_api,
    member_views,
    organization_context,
    report_views,
    views,
)

# Keep workspace resolution isolated from the large operational view module while making all
# existing views use the same session-selected organization resolver at runtime.
views.active_organization = organization_context.active_organization
master_data_views.active_organization = organization_context.active_organization
member_views.active_organization = organization_context.active_organization

urlpatterns = [
    path("health/", views.health, name="health"),
    path("ready/", views.readiness, name="readiness"),
    path("api/device/uploads/open/", device_api.upload_open, name="device-upload-open"),
    path("api/device/pairing/", device_api.pairing_create, name="device-pairing-create"),
    path("api/device/pairing/<uuid:pairing_id>/claim/", device_api.pairing_claim, name="device-pairing-claim"),
    path("api/device/heartbeat/", device_api.heartbeat, name="device-heartbeat"),
    path("api/device/commands/", device_api.command_poll, name="device-command-poll"),
    path("api/device/capture-context/", device_api.capture_context, name="device-capture-context"),
    path("api/device/commands/<uuid:command_id>/ack/", device_api.command_acknowledge, name="device-command-ack"),
    path("api/devices/<uuid:device_id>/commands/", device_api.command_create, name="device-command-create"),
    path("api/analyses/", analysis_api.analyses_create, name="api-analyses-create"),
    path("api/media/<uuid:media_id>/grant/", media_access.create_media_grant, name="media-object-grant"),
    path("api/media/<uuid:media_id>/timeline/", media_timeline_api.media_timeline, name="media-timeline"),
    path("media/<uuid:media_id>/object/", media_access.download_media_object, name="media-object-download"),
    path("api/analyses/<uuid:analysis_id>/", analysis_api.analysis_detail, name="api-analysis-detail"),
    path("api/device/uploads/<uuid:upload_id>/chunk/", device_api.upload_chunk, name="device-upload-chunk"),
    path("api/device/uploads/<uuid:upload_id>/finalize/", device_api.upload_finalize, name="device-upload-finalize"),
    path("", views.dashboard, name="dashboard"),
    path("workspaces/", organization_context.workspaces, name="workspaces"),
    path("workspaces/<uuid:organization_id>/select/", organization_context.workspace_switch, name="workspace-switch"),
    path("operate/", views.operate, name="operate"),
    path("gymnasts/", master_data_views.gymnasts, name="gymnasts"),
    path("gymnasts/new/", views.gymnast_create, name="gymnast-create"),
    path("gymnasts/archived/", master_data_views.archived_gymnasts, name="gymnasts-archived"),
    path("gymnasts/<uuid:gymnast_id>/edit/", master_data_views.gymnast_edit, name="gymnast-edit"),
    path("gymnasts/<uuid:gymnast_id>/archive/", master_data_views.gymnast_archive, name="gymnast-archive"),
    path("gymnasts/<uuid:gymnast_id>/merge/", master_data_views.gymnast_merge, name="gymnast-merge"),
    path("gymnasts/<uuid:gymnast_id>/restore/", master_data_views.gymnast_restore, name="gymnast-restore"),
    path("levels/", master_data_views.levels, name="levels"),
    path("levels/new/", master_data_views.level_create, name="level-create"),
    path("levels/<uuid:level_id>/edit/", master_data_views.level_edit, name="level-edit"),
    path("levels/<uuid:level_id>/archive/", master_data_views.level_archive, name="level-archive"),
    path("organization/members/", member_views.members, name="members"),
    path("organization/members/new/", member_views.member_create, name="member-create"),
    path("organization/members/<int:membership_id>/edit/", member_views.member_edit, name="member-edit"),
    path("organization/invitations/", invitation_views.invitation_list, name="membership-invitations"),
    path("organization/invitations/new/", invitation_views.invitation_create, name="membership-invitation-create"),
    path("organization/invitations/<uuid:invitation_id>/revoke/", invitation_views.invitation_revoke, name="membership-invitation-revoke"),
    path("invite/<str:token>/", invitation_views.invitation_accept, name="membership-invitation-accept"),
    path("devices/", views.devices, name="devices"),
    path("analyses/", views.analyses, name="analyses"),
    path("reviews/", views.review_inbox, name="review-inbox"),
    path("reviews/<uuid:job_id>/assign/", views.review_assign, name="review-assign"),
    path("analyses/<uuid:job_id>/cancel/", views.analysis_cancel, name="analysis-cancel"),
    path("competitions/", views.competitions, name="competitions"),
    path("competitions/routines/<uuid:routine_id>/kiga.json", views.kiga_routine_export, name="kiga-routine-export"),
    path("analyses/<uuid:job_id>/review/", views.analysis_review, name="analysis-review"),
    path("analyses/<uuid:job_id>/annotations/new/", annotation_views.annotation_create, name="annotation-create"),
    path("analyses/<uuid:job_id>/score-review/", views.score_comparison_review, name="score-comparison-review"),
    path("analyses/deductions/<uuid:candidate_id>/decision/", views.review_decision, name="review-decision"),
    path("imports-exports/", views.exchange, name="exchange"),
    path("imports-exports/kiga/preview/", views.kiga_import_preview, name="kiga-import-preview"),
    path("imports-exports/kiga/commit/", views.kiga_import_commit, name="kiga-import-commit"),
    path("imports-exports/gymnasts/commit/", views.gymnast_import_commit, name="gymnast-import-commit"),
    path("imports-exports/gymnasts.csv", views.gymnast_export, name="gymnast-export"),
    path("imports-exports/reviewed-labels.json", views.reviewed_labels_export, name="reviewed-labels-export"),
    path("imports-exports/gymnasts/errors.csv", views.gymnast_import_errors, name="gymnast-import-errors"),
    path("system/status/", views.system_status, name="system-status"),
    path("system/storage/", views.storage_settings, name="storage-settings"),
    path("system/backups/", views.system_backups, name="system-backups"),
    path("system/backups/<uuid:backup_id>/manifest/", views.backup_manifest, name="backup-manifest"),
    path("system/backups/<uuid:backup_id>/restore-preflight/", views.backup_restore_preflight, name="backup-restore-preflight"),
    path("system/updates/", views.system_updates, name="system-updates"),
    path("organization/select/", governance_views.organization_select, name="organization-select"),
    path("organization/invitations/accept/", governance_views.invitation_accept, name="invitation-accept"),
    path("administration/governance/", governance_views.governance_admin, name="governance-admin"),
    path("administration/members/invite/", governance_views.member_invite, name="member-invite"),
    path("administration/members/<int:membership_id>/change/", governance_views.member_change, name="member-change"),
    path("administration/configuration/create/", governance_views.configuration_create, name="configuration-create"),
    path("administration/datasets/register/", governance_views.dataset_register, name="dataset-register"),
    path("administration/evidence-shares/create/", governance_views.evidence_share_create, name="evidence-share-create"),
    path("administration/evidence-shares/<uuid:grant_id>/revoke/", governance_views.evidence_share_revoke, name="evidence-share-revoke"),
    path("evidence-shares/redeem/", governance_views.evidence_share_redeem, name="evidence-share-redeem"),
    path("administration/audit.csv", governance_views.audit_export, name="audit-export"),
    path("administration/datasets.json", governance_views.dataset_governance_export, name="dataset-governance-export"),
    path("reports/", report_views.reports, name="reports"),
    path("reports/<uuid:report_id>/", report_views.report_detail, name="report-detail"),
    path("reports/<uuid:report_id>/report.json", report_views.report_json, name="report-json"),
    path("reports/score/<uuid:job_id>/generate/", report_views.score_report_generate, name="score-report-generate"),
    path("reports/structured/publish/", report_views.structured_report_publish, name="structured-report-publish"),
    path("reports/pipeline/<uuid:job_id>/publish/", report_views.pipeline_artifact_publish, name="pipeline-artifact-publish"),
    path("reports/competitions/<uuid:event_id>/plan/", report_views.competition_batch_plan, name="competition-batch-plan"),
    path("reports/competition-batches/<uuid:batch_id>/batch.json", report_views.competition_batch_json, name="competition-batch-json"),
]
